### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Poussinou** [maksim-m/Popular-Movies-App#13]
Hi @maksim-m 
Since the app is licensed under Apache License, can you consider adding this app to the F-Droid repository? (I don't know if you're using proprietary libraries, but it doesn't works with F-Droid)

I can give you documentation and links if you need it ;)

**Comment by maksim-m** [comment]
Hi, thank you for your suggestion.
However, this project was created for educational purposes and is no longer maintained, so I don't plan to publish the app.

**Comment by Poussinou** [comment]
Ok no problem :+1:

**Comment by IzzySoft** [comment]
@maksim-m if you no longer maintain this app, may I suggest you say so prominently in the README of the project – or even archive the project (via its settings) to make the fact more obvious?
